name: "Setup cache"
description: "Setup cache"

inputs:
  key:
    description: "subkey of the cache"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Rust toolchain
      uses: actions/cache@v3
      with:
        key: cargo
        path: |
          ~/.cargo
    - name: Cache sccache DB 0
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-0
        path: |
          ~/.cache/sccache/0
    - name: Cache sccache DB 1
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-1
        path: |
          ~/.cache/sccache/1
    - name: Cache sccache DB 2
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-2
        path: |
          ~/.cache/sccache/2
    - name: Cache sccache DB 3
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-3
        path: |
          ~/.cache/sccache/3
    - name: Cache sccache DB 4
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-4
        path: |
          ~/.cache/sccache/4
    - name: Cache sccache DB 5
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-5
        path: |
          ~/.cache/sccache/5
    - name: Cache sccache DB 6
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-6
        path: |
          ~/.cache/sccache/6
    - name: Cache sccache DB 7
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-7
        path: |
          ~/.cache/sccache/7
    - name: Cache sccache DB 8
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-8
        path: |
          ~/.cache/sccache/8
    - name: Cache sccache DB 9
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-9
        path: |
          ~/.cache/sccache/9
    - name: Cache sccache DB a
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-a
        path: |
          ~/.cache/sccache/a
    - name: Cache sccache DB b
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-b
        path: |
          ~/.cache/sccache/b
    - name: Cache sccache DB c
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-c
        path: |
          ~/.cache/sccache/c
    - name: Cache sccache DB d
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-d
        path: |
          ~/.cache/sccache/d
    - name: Cache sccache DB e
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-e
        path: |
          ~/.cache/sccache/e
    - name: Cache sccache DB f
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}-sccache-db-f
        path: |
          ~/.cache/sccache/f
    