[package]
name = "phala-rocket-middleware"
version = "0.1.0"
edition = "2021"

description = "Some Rocket middleware used by Phala"
license = "Apache-2.0"
repository = "https://github.com/Phala-Network/phala-blockchain"

[dependencies]
rocket = "0.5.0"
log = "0.4.16"
