[package]
name = "sfq-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }
phala-scheduler = { path = "../../crates/phala-scheduler" }
clap = { version = "4.0.32", features = ["derive"] }
