[workspace]

[profile.release]
strip = true

[package]
edition = "2021"
name = "sideprog"
version = "0.1.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.16"
sidevm = { version = "0.1", path = "../../../sidevm/sidevm" }
phala-allocator = { version = "0.1", path = "../../../phala-allocator" }
hex_fmt = "0.3.0"
scale = { package = "parity-scale-codec", version = "3.6.5" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
this-crate = "0.1.0"

[dev-dependencies]
insta = "1.21.0"
