[package]
name = "pruntime"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[dependencies]
libc = "0.2"
log         = "0.4.14"
env_logger  = { version = "0.9.0", default-features = false, features = ["termcolor"] }
anyhow      = "1.0"
lazy_static = { version = "1.4.0", default-features = false }
parity-scale-codec = { version = "2", default-features = false }

phactory = { path = "../../../crates/phactory" }
phactory-pal = { path = "../../../crates/phactory/pal" }
phactory-api = { path = "../../../crates/phactory/api" }
phala-allocator = { path = "../../../crates/phala-allocator" }

serde = { version = "1.0", default-features = false, features = ["derive"] }

num_cpus = "1.13"
envy = "0.4.2"

# for api server
rocket         = "0.4.7"
rocket_contrib = { version = "0.4.5", features = ["json"]}
rocket_codegen = "0.4.5"
rocket_cors = "0.5.2"
serde_json = "1.0"
colored = "2"

structopt = "0.3.21"
