[package]
name = "pink-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
sp-weights = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pink-capi = { path = "../capi" }
im = "15"
once_cell = "1"
libc = "0.2"
log = "0.4"
phala-crypto = { path = "../../phala-crypto" }
pink-extension-runtime = { path = "../pink-extension-runtime" }
environmental = "1"
