[package]
name = "substrate-subxt-proc-macro"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
autotests = false

[lib]
proc-macro = true

[dependencies]
heck = "0.3.1"
proc-macro2 = "1.0.10"
proc-macro-crate = "0.1.4"
quote = "1.0.3"
syn = "1.0.17"
synstructure = "0.12.3"

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
codec = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive", "full"] }
env_logger = "0.7.1"
frame-support = { version = "2.0.0-dev", package = "frame-support", path = "../../substrate/frame/support" }
pretty_assertions = "0.6.1"
sp-core = { version = "2.0.0-dev", package = "sp-core", path = "../../substrate/primitives/core" }
sp-keyring = { version = "2.0.0-dev", package = "sp-keyring", path = "../../substrate/primitives/keyring" }
sp-runtime = { version = "2.0.0-dev", package = "sp-runtime", path = "../../substrate/primitives/runtime" }
substrate-subxt = { path = ".." }
trybuild = "1.0.25"

[[test]]
name = "balances"
path = "tests/balances.rs"
