[package]
description = "The memory allocator for Phala pruntime"
license = "Apache-2.0"
homepage = "https://github.com/Phala-Network/phala-blockchain"
name = "phala-allocator"
version = "0.1.0"
edition = "2018"

[dependencies]
