[package]
edition = "2021"
name = "pruntime"
version = "2.0.0"

[profile.release]
panic = "abort"

[dependencies]
anyhow = "1.0"
clap = {version = "3", features = ["derive"]}
colored = "2"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "socks", "blocking"] }
reqwest-env-proxy = {path = "../../crates/reqwest-env-proxy"}
libc = "0.2"
log = "0.4.14"
num_cpus = "1.13"
os_pipe = "1.0.0"
version = "3.0.0"

rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_cors = { version = "0.6.0-alpha1", git = "https://github.com/lawliet89/rocket_cors" }
serde_json = "1.0"

base64 = "0.13.0"

env_logger = {version = "0.9.0", features = ["termcolor"]}
lazy_static = {version = "1.4.0", default-features = false}
parity-scale-codec = {version = "3.0", default-features = false}
serde = {version = "1.0", default-features = false, features = ["derive"]}
urlencoding = "2.1.0"

phactory = {path = "../../crates/phactory"}
phactory-api = {path = "../../crates/phactory/api"}
phactory-pal = {path = "../../crates/phactory/pal"}
phala-allocator = {path = "../../crates/phala-allocator"}
phala-rocket-middleware = {path = "../../crates/phala-rocket-middleware"}

[patch.crates-io]
# TODO.kevin: Remove this patch when https://github.com/SergioBenitez/Rocket/pull/2269 launched
rocket = { git = "https://github.com/kvinwang/Rocket.git", branch = "fix-2268" }
