[package]
authors = ['Phala.network']
edition = '2018'
name = 'pallet-phala'
version = "2.0.0-rc2"
license = "Apache 2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

chrono = { version = "0.4", default-features = false, features = ["serde"] }
itertools = { version = "0.8", default-features = false }
untrusted = { version = "0.7" }
base64 = { version = "0.11", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false }
webpki = { path = "../../webpki", default_features = false }
ring = { path = "../../ring", default_features = false, features = ["alloc"] }
# serde_json_core = {}

[dependencies.frame-support]
default-features = false
version = "2.0.0-rc2"
path = "../../substrate/frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0-rc2"
path = "../../substrate/frame/system"

[dev-dependencies.sp-core]
default-features = false
version = "2.0.0-rc2"
path = "../../substrate/primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-rc2"
path = "../../substrate/primitives/io"

[dev-dependencies.sp-runtime]
default-features = false
version = "2.0.0-rc2"
path = "../../substrate/primitives/runtime"

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std'
]
