[package]
name = "phost"
version = "0.1.0"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures_03 = { package = "futures", version = "0.3.0", features = ["compat"] }
tokio = { version = "0.2", features = ["full"] }
tokio-compat = { git = "https://github.com/tokio-rs/tokio-compat.git" }
hyper = { version = "0.13" }
hex = { version = "*" }
base64 = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"
bytes = "0.5"

pnode-runtime = { path = "../node/runtime", package = "experimental-node-runtime" }
subxt = { path = "../substrate-subxt", package = "substrate-subxt" }
system = { version = "2.0.0", path = "../substrate/frame/system", package = "frame-system" }
sp-rpc = { version = "2.0.0", path = "../substrate/primitives/rpc", package = "sp-rpc" }
sp-runtime = { version = "2.0.0", path = "../substrate/primitives/runtime", package = "sp-runtime" }
sc-finality-grandpa = { version = "2.0.0", path = "../substrate/client/finality-grandpa", package = "sc-finality-grandpa" }
codec = { package = 'parity-scale-codec', version = '1.0.0' }
