[package]
name = "phost"
version = "0.1.0"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnode-runtime = { package = "experimental-node-runtime", path = "../node/runtime" }
subxt = { package = "substrate-subxt", path = "../substrate-subxt" }
tokio = "0.1"
system = { package = "frame-system", path = "../substrate/frame/system" }
sp-rpc = { package = "sp-rpc", path = "../substrate/primitives/rpc" }
sp-runtime = { package = "sp-runtime", path = "../substrate/primitives/sr-primitives" }
sc-finality-grandpa = { package = "sc-finality-grandpa", path = "../substrate/client/finality-grandpa"}
hex = { package = "hex" }

codec = { package = 'parity-scale-codec', version = '1.0.0' }