[package]
description = "Mock pink chain extension for Phala pink contract"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
name = "pink-extension-runtime"
version = "0.4.5"
edition = "2021"

[dependencies]
pink-extension = { version = "0.4.2", path = "../pink-extension" }
reqwest-env-proxy = { version = "0.1", path = "../../reqwest-env-proxy" }
sp-core = { version = "21", features = ["full_crypto"] }
sp-runtime-interface = { version = "17", features = ["disable_target_static_assertions"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "socks", "trust-dns"] }
log = "0.4"
ring = "0.16"
getrandom = "0.2"
once_cell = "1.10.0"
hex_fmt = "0.3.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
