[package]
name = "pallet-offences-benchmarking"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME offences pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/benchmarking" }
frame-support = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/system" }
pallet-babe = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/babe" }
pallet-balances = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/balances" }
pallet-grandpa = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/grandpa" }
pallet-im-online = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/im-online" }
pallet-offences = { version = "2.0.0", default-features = false, features = ["runtime-benchmarks"], path = "../../../substrate/frame/offences" }
pallet-session = { version = "2.0.0", default-features = false, path = "../../../substrate/frame/session" }
pallet-staking = { package = "phala-staking", version = "2.0.0", default-features = false, features = ["runtime-benchmarks"], path = "../../staking" }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../../substrate/primitives/runtime" }
sp-staking = { version = "2.0.0", default-features = false, path = "../../../substrate/primitives/staking" }
sp-std = { version = "2.0.0", default-features = false, path = "../../../substrate/primitives/std" }

[dev-dependencies]
pallet-staking-reward-curve = { version = "2.0.0", path = "../../../substrate/frame/staking/reward-curve" }
pallet-timestamp = { version = "2.0.0", path = "../../../substrate/frame/timestamp" }
serde = { version = "1.0.101" }
sp-core = { version = "2.0.0", path = "../../../substrate/primitives/core" }
sp-io = { version = "2.0.0", path = "../../../substrate/primitives/io" }

[features]
default = ["std"]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",
	"codec/std",
]
