[package]
edition = "2021"
name = "pink-sidevm"
version = "0.1.0"

[dependencies]
hyper = {version = "0.14.18", features = ["server"]}
pink-sidevm-env = {version = "0.1.0", path = "../env"}
pink-sidevm-logger = {version = "0.1.0", path = "../logger"}
pink-sidevm-macro = {version = "0.1.0", path = "../macro"}
tokio = {version = "1"}
log = "0.4.16"
