[package]
name = "enclave-api"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chain = { path = "../../runtime", default-features = false, package = "phala-node-runtime" }
sp-finality-grandpa = { package = "sp-finality-grandpa", path = "../../../substrate/primitives/finality-grandpa", default-features = false }
parity-scale-codec   = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-system = { package = "frame-system", path = "../../../substrate/frame/system", default-features = false }
sp-core = { package = "sp-core", path = "../../../substrate/primitives/core", default-features = false, features = ["full_crypto"] }
sp-application-crypto = { package = "sp-application-crypto", path = "../../../substrate/primitives/application-crypto", default-features = false, features = ["full_crypto"] }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false }
trie-storage = { path = "../../../crates/trie-storage", default-features = false, features = ["serde"] }
phala-types = { path = "../../../common/types", default-features = false }
serde = { version = "1", optional = true, features = ["derive"], default-features = false }
base64 = { version = "0.13" }
derive_more = "0.99.16"
prpc = { path = "../../../crates/prpc" }
prost = { version = "0.8.0", default-features = false }
phala-crypto = { path = "../../../crates/crypto" }
phala-mq = { path = "../../../crates/phala-mq" }

# for pruntime_client
async-trait = { version = "0.1.51", optional = true }
anyhow = { version = "1.0.43", optional = true }
log = { version = "0.4.14", optional = true }
reqwest = { version = "0.11.4", optional = true }

[build-dependencies]
prpc-build = { path = "../../../crates/prpc-build", optional = true }
tera = { version = "1.12.1", optional = true }
tempdir = { version = "0.3.7", optional = true }


[features]
default = ["std", "pruntime-client"]

std = [
    "serde",
    "trie-storage/serde",
    "sp-core/full_crypto",
    "sp-runtime/std",
    "sp-application-crypto/std",
    "frame-system/std",
    "chain/std",
    "prpc-build",
    "tera",
    "tempdir",
]

sgx = []
pruntime-client = [
    "async-trait",
    "anyhow",
    "log",
    "reqwest",
]

