[package]
name = "debug-cli"
version = "0.1.0"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.11"
codec = { package = "parity-scale-codec", version = "2.1" }
hex = "0.4"
structopt = "0.3"

sp-runtime = { path = "../../substrate/primitives/runtime" }
frame-support = { path = "../../substrate/frame/support" }
sc-finality-grandpa = { path = "../../substrate/client/finality-grandpa" }

phala-types = { path = "../../common/types" }
phala-pallets = { path = "../../pallets/phala" }
enclave-api = { path = "../../standalone/pruntime/enclave-api" }
phala-crypto = { path = "../../crates/crypto" }
