name: Build on Ubuntu 18.04 and publish the docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ secrets.PACKAGE_MANAGER_USERNAME }}
        password: ${{ secrets.PACKAGE_MANAGER_TOKEN }}
        registry: docker.pkg.github.com
        repository: phala-network/phala-blockchain/phala-blockchain
        tag_with_ref: true
        tag_with_sha: true
